package com.bank.islamic.shariahsupervisoryboarddirectory;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

/**
 * BIAN Service Domain: Shariah Supervisory Board Directory
 *
 * Business Area:      Shariah Governance and Compliance
 * Business Domain:    Shariah Governance
 * Functional Pattern: Catalog
 * Asset Type:         SSB Member Mandate
 * Control Record:     SSB Member Mandate Directory Entry
 *
 * Generated by the islamic-platform service generator (Phase 1 — shallow build).
 * Replace the in-memory store with real persistence and domain logic in Phase 2.
 */
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Bean
    public OpenAPI openApi() {
        return new OpenAPI().info(new Info()
                .title("Shariah Supervisory Board Directory — BIAN Semantic API")
                .description("Service Domain 'Shariah Supervisory Board Directory' (Catalog pattern) "
                        + "operating on the 'SSB Member Mandate Directory Entry' control record.")
                .version("0.1.0"));
    }
}
